CREATE TABLE coupon
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id     UUID           NOT NULL UNIQUE,
    code            VARCHAR(6)     NOT NULL UNIQUE,
    description     VARCHAR(500)   NOT NULL,
    coupon_status   INTEGER        NOT NULL,
    discount_value  NUMERIC(10, 2) NOT NULL,
    expiration_date DATE           NOT NULL,
    published       BOOLEAN        NOT NULL,
    redeemed        BOOLEAN        NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

